services:
    postgres:
        image: postgres:16.3
        container_name: triads-postgres
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432

#  redis:
#    image: redis:7.2.5
#    container_name: triads-redis
#    env_file:
#      - .env
#    restart: unless-stopped
#    ports:
#      - ${REDIS_PORT}:6379

volumes:
    data:
        driver: local

networks:
    app-tier:
        driver: bridge
